version: 2
build:
  os: ubuntu-latest
  tools:
    python: "3.9"
  apt_packages:
    - graphviz

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
   install:
     - method: pip
       extra_requirements:
        - docs
       path: .

# Don't build any extra formats
formats: []
