resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astropy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

schedules:
- cron: '0 0 * * 0'
  displayName: 'Weekly cron'
  branches:
    include:
    - master
  always: 'true'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    posargs: --openmp-expected=True
    coverage: codecov
    envs:
    # Code style
    - linux: style
    # Docs
    - linux: build_docs
    # Standard tests
    - linux: py36-test
    - linux: py37-test
    - linux: py38-test
    - linux: py38-test-dev
    - macos: py36-test
      posargs: --openmp-expected=False
    - macos: py38-test-dev
      posargs: --openmp-expected=False
    # Test with more compilers, for the OpenMP helpers
    - linux: py38-test-linuxgcc-conda

# Cannot run with conda due to missing rc.exe
- job: 'Windows'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: |
      python -m pip install --upgrade tox
      tox -e py36-test
    displayName: 'Run standard tests'
  - script: |
      tox -e py38-test-dev
    displayName: 'Run dev tests'

# Cannot run with conda due to missing C compilers
- job: 'OSX_OpenMP'
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: |
      python -m pip install --upgrade tox
      tox -e py38-test-osxgcc-conda
    displayName: 'OSX with gcc'
# TODO: This fails and need fixing by someone who cares
#       about OSX and clang.
#  - script: |
#      tox -e py38-test-osxclang-conda
#    displayName: 'OSX with clang'